name: Build and Push Docker Image

on:
  release:
    types: [ published ]

jobs:
  UnitTest:
    uses: ./.github/workflows/unit-tests.yaml

  extract-tag:
    steps:
      - name: Extract Release Tag
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

  build-and-push:
    needs:
      - UnitTest
    uses: ./.github/workflows/docker-build.yaml
    inputs:
      TAG: ${{ env.TAG }}
