name: Build and Push Docker Image

on:
  release:
    types: [ published ]

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yaml

  extract-tag:
    steps:
      - name: Extract Release Tag
        id: get_tag
        run: |
          echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "IS_PRERELEASE=${{ github.event.release.prerelease }}" >> $GITHUB_ENV

  build-and-push:
    needs:
      - unit-tests
      - extract-tag
    uses: ./.github/workflows/docker-build.yaml
    with:
      VERSION_TAG: ${{ env.VERSION_TAG }}
      IS_PRERELEASE: ${{ env.IS_PRERELEASE }}
      IS_LATEST: true
